//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogger
{
    using System;
    
    public enum TeamRole : int
    {
        TOP = 0,
        SUPPORT = 1,
        ADC = 2,
        MID = 3,
        JUNGLE = 4
    }
}
